### ISSUE TITLE
FindItems fails with new property

### ISSUE THREAD

**Issue by RobGray-au** [michelderooij/Remove-DuplicateItems#5]
_Error Exception calling "FindItems" with "1" argument(s): "The property Mentions is valid only for Exchange Exchange2015_

also.. property _Hashtags_

My EXS is on-prem, 2016 CU19.  [Version 15.1 ‎(Build 2176.2)‎]

there is no way to change the EWS version to 2015 as the highest appears to be Exchange2013_SP1, which i think i have set already.

```
                $ItemView.PropertySet= New-Object Microsoft.Exchange.WebServices.Data.PropertySet( [Microsoft.Exchange.WebServices.Data.BasePropertySet]::FirstClassProperties)
                $ItemView.PropertySet.Add( $PidTagSearchKey)
```

can / should the PropertySet be reduced to specific items (reducing FirstClassProperties) to search or does that then cause issues for determing duplicates for other than IPM.Note types..

**Comment by RobGray-au** [comment]
tried updating to EWS2.2.1 which then has a problem with `$SfSearchFilter = new-object Microsoft.Exchange.WebServices.Data.SearchFilter+IsEqualTo([Microsoft.Exchange.WebServices.Data.FolderSchema]::DisplayName,$fldArray[$lint])`  error with 2 parameters.

**Comment by michelderooij** [comment]
Should be fixed by now. Please re-open when it still happens.
