### ISSUE TITLE
Parameter set cannot be resolved

### ISSUE THREAD

**Issue by cht47** [michelderooij/Remove-DuplicateItems#7]
![image](https://user-images.githubusercontent.com/2283180/120996159-5f19bf00-c786-11eb-8548-5bcdb54968ae.png)

Hi, no matter which tutorial I use, your blog article with the given examples nor my own parameter, I always get the same parameter error. With other Scripts, like WSUS Clean I have zero problems.

**Comment by jpkool** [comment]
I get the exact same issue. Has this been resolved ?

**Comment by PeRogger** [comment]
Hi I do have this issue as well. How to I fix this?
Best Regards
Peter

**Comment by michelderooij** [comment]
Missing one of the authentication methods, or use UseDefaultCredentials to operate against Exchange on-premises with current context.
