### ISSUE TITLE
Error Message "Problem initializing test-object from module Microsoft.Identity.Client"

### ISSUE THREAD

**Issue by ITEngineer-0815** [michelderooij/Remove-DuplicateItems#8]
Hello!

The script does not work.

After I started it, I get the following error message:

============================
Import-ModuleDLL : Problem initializing test-object from module Microsoft.Identity.Client: Cannot find type [Microsoft.Identity.Client.CacheOptions]: verify that the assembly containing
this type is loaded.
At D:\Scripts\Remove-DuplicateItems\Remove-DuplicateItems.ps1:1380 char:5
+     Import-ModuleDLL -Name 'Microsoft.Identity.Client' -FileName 'Mic ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-ModuleDLL
============================

**Comment by michelderooij** [comment]
This should be addressed in the most recent update.
