### ISSUE TITLE
Cannot bind to MsgFolderRoot & ArchiveMsgFolderRoot

### ISSUE THREAD

**Issue by Dalong0** [michelderooij/Remove-DuplicateItems#9]
Hello,

Tying running this script with modern Auth : .\Remove-DuplicateItems.ps1 -Mailbox mail@domain.tld -Type Mail -DeleteMode HardDelete -Mode Full -Retain Oldest -Verbose -Server outlook.office365.com -TenantId "TenantID" -ClientId "ClientID" -Secret $secret

I am getting this error:
WARNING: Cannot bind to MsgFolderRoot: Exception calling "Bind" with "2" argument(s): "Credentials are required to make a service request."
WARNING: Cannot bind to ArchiveMsgFolderRoot: Exception calling "Bind" with "2" argument(s): "Credentials are required to make a service request."
![image](https://user-images.githubusercontent.com/47578986/189535365-414bd559-c779-4c66-a236-d6518da08dfd.png)

Permissions gived to the application here :
![image](https://user-images.githubusercontent.com/47578986/189535455-0fae0dda-2bb1-43b2-8bdd-55cc83bec506.png)

Can you help ?

Thanks

**Comment by michelderooij** [comment]
The full_access_as_app should suffice. 
You granted consent for the application?

**Comment by michelderooij** [comment]
Closed to to age - feel free to reopen

**Comment by JoshBritton5544** [comment]
Hello,

I am seeing this error as well. I have confirmed the full_access_as_app permisson, as well as the admin consent on the app registration. Do you have any additional troubleshooting steps for this issue?

**Comment by michelderooij** [comment]
Pushed 2.44, which sets credentials when using OAuth, which according to other reports might prevent this anomaly.
Please report any feedback as I could not repro the issue.

**Comment by joshuawi99** [comment]
> Pushed 2.44, which sets credentials when using OAuth, which according to other reports might prevent this anomaly. Please report any feedback as I could not repro the issue.

Im still having this Issue were this error appears:

AUSFÜHRLICH: Module Microsoft.Exchange.WebServices v2.2.1.0 already loaded
AUSFÜHRLICH: Module Microsoft.Identity.Client v4.25.0.0 already loaded
AUSFÜHRLICH: Will use provided secret to authenticate
AUSFÜHRLICH: Authentication token acquired
AUSFÜHRLICH: Cleanup Mode: Mailbox
Processing mailbox ******************
AUSFÜHRLICH: Using *********** for impersonation
AUSFÜHRLICH: Using Exchange Web Services URL https://outlook.office365.com/EWS/Exchange.asmx
AUSFÜHRLICH: Constructing folder matching rules
WARNUNG: Cannot bind to MsgFolderRoot: Ausnahme beim Aufrufen von "Bind" mit 2 Argument(en):  "Credentials are required to make a service request."
WARNUNG: Cannot bind to ArchiveMsgFolderRoot: Ausnahme beim Aufrufen von "Bind" mit 2 Argument(en):  "Credentials are required to make a service request."
AUSFÜHRLICH: Processing ***********  finished


Do you have any feedback for me to try out?

**Comment by tylerwasick** [comment]
I am having a similar issue. 

## Permissions
![image](https://github.com/michelderooij/Remove-DuplicateItems/assets/40273103/a717c990-2670-4d80-b6f3-0861ecd2e46a)

## Parameters
`.\Remove-DuplicateItems.ps1 -Server outlook.office365.com -TenantId $tenantId -ClientId $clientId -Secret $secretKey -Identity $User -Type Mail -DeleteMode "MoveToDeletedItems" -Report -WhatIf`

## Error
_Processing mailbox ******@*********.com (******@*********.com)
WARNING: Cannot bind to MsgFolderRoot: Exception calling "Bind" with "2" argument(s): "The request failed. The remote server returned an error: (403) ."
WARNING: Cannot bind to ArchiveMsgFolderRoot: Exception calling "Bind" with "2" argument(s): "The request failed. The remote server returned an error: (403) ."_

**Comment by joshuawi99** [comment]
You have to set "full_access_as_app" API Permissions

**Comment by michelderooij** [comment]
What Joshua said - you need to have proper API permissions assigned to the App

**Comment by tylerwasick** [comment]
Can you provide information on setting that?

**Comment by michelderooij** [comment]
This is an Exchange Web Services script. For that to work with Exchange Online and OAuth, you need to grant the registered app (Azure AD portal), after configuring App permissions and authentication method (cert/secret), configure the following API permission: Office 365 Exchange Online > full_access_as_app

For more step-by-step, check this older article on the same for Exchange Online Management access, but where it states you need to grant "Exchange and check Exchange.ManageAsApp", replace it with " Office 365 Exchange Online > full_access_as_app"

**Comment by joshuawi99** [comment]
I did excactly what you described.
These are my API Settings:
![grafik](https://github.com/michelderooij/Remove-DuplicateItems/assets/143619398/e47ffd0e-e87c-4af3-8f59-e96a30402595)

This is my command to run the skript:

$blub="***********************"   // Secret as plain text

$Secret = ConvertTo-SecureString -String $blub -AsPlainText -Force

.\Remove-DuplicateItems.ps1 -Server outlook.office365.com -Identity ***************** -Impersonation -CleanupMode Mailbox -DeleteMode MoveToDeletedItems -Mode Full -Retain Oldest -Verbose -TenantId '************************' -ClientId '**************************' -Secret $Secret

But im still getting the error as shown by others above:
![grafik](https://github.com/michelderooij/Remove-DuplicateItems/assets/143619398/5db65910-f5ad-4f7d-9f1d-a4b05d62272f)

I guess it is not a problem with the API Permission configuration or my Secret. I think it has something to do with the "dummy creds".

**Comment by joshuawi99** [comment]
Ok quick update from my side. I used the wrong secret key.
But I am still getiing a 403 error now:

![grafik](https://github.com/michelderooij/Remove-DuplicateItems/assets/143619398/23cd814a-a9b8-4f7f-b18b-c71a533535c2)

**Comment by joshuawi99** [comment]
Okay I got it running now thank you!
